spring:
  # thymelaef配置
  thymeleaf:
    cache: false
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Zl.mtcldys606910
    hikari:
      #连接池名
      pool-name: DataHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接最大存活时间（default 10min）
      idle-timeout: 1800000
      #最大连接数（default：10）
      maximum-pool-size: 10
      #从连接池返回的链接自动提交
      auto-commit: true
      #最大存活时间，0表示永久，默认半小时
      max-lifetime: 1800000
      #连接超时时间（default：30s）
      connection-timeout: 30000
      #心跳机制
      connection-test-query: SELECT 1


  redis:
    host: localhost
    port: 63796
    #操作的数据库
    database: 0
    password: Zl.mtcldys606910
    #连接超时时间
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 8
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接，默认8
        max-idle: 200
        #最小空闲连接时间，默认0
        min-idle: 5

server:
  port: 8899

#mybatis-plus 配置
mybatis-plus:
  #配置Mapper.xml映射文件的位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置mybatis-plus数据返回别名（默认为类名）
  type-aliases-package: com.zhongbin.miaoshademo.pojo

#mybatis SQL打印（方法接口所在的包不是Mapper.xml）
logging:
  level:
    com.zhongbin.miaoshademo.mapper: debug